{% set version = "1.7.4.1" %}

package:
  name: ecco_v4_py
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/ecco_v4_py/ecco_v4_py-{{ version }}.tar.gz
  sha256: b60daf40916294b514e365c06ef00f9fa35b538b7d77997a8405377e00798490

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]
  skip: true  # [win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - future
    - netcdf4
    - numpy
    - matplotlib-base
    - cartopy
    - dask
    - xarray
    - pyresample
    - python-dateutil
    - xmitgcm
    - xgcm

test:
  imports:
    - ecco_v4_py

about:
  home: https://github.com/ECCO-GROUP/ECCOv4-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python package for post processing and analyzing ECCOv4 output
  doc_url: https://ecco-v4-python-tutorial.readthedocs.io/index.html
  dev_url: https://github.com/ECCO-GROUP/ECCOv4-py

extra:
  recipe-maintainers:
    - timothyas
    - ifenty
    - owang01
