{% set version = "1.5.2" %}

package:
  name: ecco_v4_py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/ecco_v4_py/ecco_v4_py-{{ version }}.tar.gz
  sha256: a3dc8ede810a8d6d50ca7602bde5c895e503adc08896e70adaf7393ed96c68d1

build:
  number: 3
  script: {{ PYTHON }} -m pip install . -vv
  skip: True  # [py<37]
  skip: True  # [win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - future
    - pathlib
    - netcdf4
    - numpy
    - matplotlib-base
    - cartopy
    - dask
    - xarray
    - pyresample
    - python-dateutil
    - xmitgcm
    - xgcm

test:
  imports:
    - ecco_v4_py

about:
  home: https://github.com/ECCO-GROUP/ECCOv4-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python package for post processing and analyzing ECCOv4 output
  doc_url: https://ecco-v4-python-tutorial.readthedocs.io/index.html
  dev_url: https://github.com/ECCO-GROUP/ECCOv4-py

extra:
  recipe-maintainers:
    - timothyas
    - ifenty
    - owang01
